require 'rake'
require 'spree/testing_support/common_rake'

RSpec::Core::RakeTask.new

task default: :spec

desc 'Generates a dummy app for testing'
task :test_app do
  ENV['LIB_NAME'] = 'spree/blocks_i18n'
  Rake::Task['common:test_app'].invoke
end
